name: GitHub Actions 실행시켜보기

# Event : 실행되는 시점을 설정
$ main이라는 브랜치에 push 될 때 아래 Workflow를 실행

on:
  push:
    branches:
      - main

  
# 하나의 Workflow는 1개 이상의 Job으로 구성됩니다.
# 여러 Job은 기본적으로 병렬적으로 수행된다.

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

